### ISSUE TITLE
Decode function works only with binary string literals

### ISSUE THREAD

**Issue by kornelski** [plopgrizzly/aci_png#1]
https://github.com/plopgrizzly/aci_png/blob/master/src/lib.rs#L50

The function doesn't support strings nor paths. The `'static` requirement unnecessarily restricts it to literals.

It should at least accept `&str` or ideally `decode<P: AsRef<Path>>(path: P)` to accept any type of string or path-like object.

**Comment by AldaronLau** [comment]
Yes, just yesterday I noticed the `'static` is a very unnecessary restriction.  But, I think you misunderstand the function.  It's meant to be used like this:

```
let image = aci_png::decode(include_bytes!("path/to/image.png"));
```

The parameter takes png data, not a path.

**Comment by kornelski** [comment]
Ah, I see. `&[u8]` is fine then.

**Comment by AldaronLau** [comment]
I just released a new version to GitHub & crates.io fixing this issue, so I'm closing it.
