### ISSUE TITLE
Return type of as_slice

### ISSUE THREAD

**Issue by kornelski** [plopgrizzly/aci_png#2]
`as_slice` including width and height in the pixel data is very surprising. A better return type would be:

```rust
-> (u32, u32, &[u32])
```

so that all components can be easily extracted in one-liner:

```rust
let (width, height, pixels) = graphic.as_slice();
```

**Comment by AldaronLau** [comment]
I agree that would be a better design.  I'll make the change.

**Comment by AldaronLau** [comment]
Release of aci_png 0.5.0 fixes this issue, so closing.
